src/Entity/Announce.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnnounceRepository")
 */
class Announce
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Vehicle", cascade={"persist", "remove"})
     */
    private $vehicle;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="announces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="announce")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Location", mappedBy="announce")
     */
    private $locations;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $enable;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->locations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVehicle(): ?Vehicle
    {
        return $this->vehicle;
    }

    public function setVehicle(?Vehicle $vehicle): self
    {
        $this->vehicle = $vehicle;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEnable(): ?bool
    {
        return $this->enable;
    }

    public function setEnable(?bool $enable): self
    {
        $this->enable = $enable;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @param Comment $comment
     * @return $this
     */
    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAnnounce($this);
        }

        return $this;
    }

    /**
     * @param Comment $comment
     * @return $this
     */
    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAnnounce() === $this) {
                $comment->setAnnounce(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
            $location->setAnnounce($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getAnnounce() === $this) {
                $location->setAnnounce(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }

    /**
     * @param mixed $zipcode
     * @return Announce
     */
    public function setZipcode($zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param mixed $city
     * @return Announce
     */
    public function setCity($city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getFullAddress()
    {
        return $this->address . ", ". $this->zipcode . " " . $this->city;
    }

    public function objectToJSON()
    {
        $announce = [];
        $announce['id'] = $this->getId();
        $announce['price'] = $this->getPrice();
        $announce['zipCode'] = $this->getZipcode();
        $announce['address'] = $this->getAddress();
        $vehiculeObje =  $this->getVehicle();
        $vehicule = [];
        $vehicule['brand'] = $vehiculeObje->getBrand();
        $vehicule['model'] = $vehiculeObje->getModel();
        $vehicule['year'] = $vehiculeObje->getYear();
        $vehicule['autonomy'] = $vehiculeObje->getAutonomy();
        $announce['vehicule'] = $vehicule;

        return $announce;
    }

    public function __toString()
    {
        return $this->id . " - ". $this->address . " " . $this->city;
    }
}

src/Controller/PaymentController.php
<?php

namespace App\Controller;

use App\Entity\Location;
use App\Entity\User;
use App\Repository\LocationRepository;
use Dompdf\Dompdf;
use Dompdf\Options;
use Nzo\UrlEncryptorBundle\Annotations\ParamDecryptor;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Stripe\Checkout\Session;
use Stripe\Stripe;
use Swift_Attachment;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Routing\Annotation\Route;

class PaymentController extends AbstractController
{
    private $kernel;

    public function __construct(KernelInterface $appKernel)
    {
        $this->kernel = $appKernel;
    }

    /**
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @Route("/payment", name="payment")
     */
    public function index()
    {
        $stripe = new Stripe();
        $stripe::setApiKey('sk_test_jWWKdFyljvdnfJbjevs74kQH000tfdnAdA');

        $session = Session::create([
            'payment_method_types' => ['card'],
            'line_items' => [[
                'name' => 'T-shirt',
                'description' => 'Comfortable cotton t-shirt',
                'images' => ['https://example.com/t-shirt.png'],
                'amount' => 500,
                'currency' => 'eur',
                'quantity' => 1,
            ]],
            'success_url' => 'https://example.com/success',
            'cancel_url' => 'https://example.com/cancel',
        ]);

        return $this->render('payment/index.html.twig', [
            'controller_name' => 'PaymentController',
        ]);
    }

    /**
     * @Route("/payment/success/{locationId}", name="successPayment")
     * @ParamDecryptor(params={"locationId"})
     * @param \Swift_Mailer $mailer
     * @param string $locationId
     * @return RedirectResponse|Response
     */
    public function successPayment(\Swift_Mailer $mailer, string $locationId)
    {
        $em           = $this->getDoctrine()->getManager();
        /** @var LocationRepository $repoLocation */
        $repoLocation = $em->getRepository(Location::class);

        /** @var Location $location */
        if ($location = $repoLocation->find($locationId)) {
            $message = (new \Swift_Message('E-motion: Paiement effectuée'))
                ->setFrom('admin@e-motion.fr')
                ->setTo($location->getUser()->getEmail())
                ->setBody(
                    $this->renderView(
                        'payment/partials/_email.html.twig'
                    ),
                    'text/html'
                )
            ;

            $this->generatePDF($location, 'facture');
            $this->generatePDF($location, 'contrat');

            $message->attach(Swift_Attachment::fromPath(
                $this->kernel->getProjectDir() . '/public/uploads/pdf/factures/facture_'. $location->getId() .'.pdf',
                'application/pdf'
            ));
            $message->attach(Swift_Attachment::fromPath(
                $this->kernel->getProjectDir() . '/public/uploads/pdf/contrats/contrat_'. $location->getId() .'.pdf',
                'application/pdf'
            ));

            $mailer->send($message);

            /** @var User $user */
            $user      = $location->getUser();

            $user->setLoyaltyPoints($this->getLoyaltyPoint($user, $location->getPricePaid()));
            $location->getAnnounce()->setEnable(false);
            $em->persist($location);
            $em->flush();

            return $this->redirectToRoute('home');
        }
        return $this->render('payment/index.html.twig');
    }

    /**
     * @param User $user
     * @param int $pricePaid
     * @return int|mixed
     */
    public function getLoyaltyPoint(User $user, int $pricePaid)
    {
        $loyaltyPoints = $user->getLoyaltyPoints();
        $loyaltyPoints += $pricePaid;

        return $loyaltyPoints;
    }

    /**
     * @param Location $location
     * @param string $type
     */
    public function generatePDF(Location $location, string $type)
    {
        $html       = $pdfFilepath = "";
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        $pdf = new Dompdf($pdfOptions);

        if ($type == "facture") {
            $html = $this->renderView('payment/partials/_facture.html.twig', ['location' => $location]);
        } elseif ($type == "contrat") {
            $html = $this->renderView('payment/partials/_contrat.html.twig', ['location' => $location]);
        }

        $pdf->loadHtml($html);
        $pdf->setPaper('A4', 'portrait');
        $pdf->render();

        $output = $pdf->output();

        if ($type == "facture") {
            $publicDirectory = $this->kernel->getProjectDir() . '/public/uploads/pdf/factures';
            $pdfFilepath =  $publicDirectory . '/facture_'.$location->getId().'.pdf';
        } elseif ($type == "contrat") {
            $publicDirectory = $this->kernel->getProjectDir() . '/public/uploads/pdf/contrats';
            $pdfFilepath =  $publicDirectory . '/contrat_'.$location->getId().'.pdf';
        }

        file_put_contents($pdfFilepath, $output);
    }
}

templates/payment/partials/_contrat.html.twig
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <div class="jumbotron">
            <h3>Contrat de location</h3>
            <p>Utilisateurs : {{ location.user.fullName }}</p>
            <p>Adresse : {{ location.user.fullAddress }}</p>
        </div>
        <p>
            <h3>1.1 – Nature et date d’effet du contrat</h3>
            Le loueur met à disposition du locataire, un véhicule de marque {{ location.vehicle.brand }}, immatriculé {{ location.vehicle.matriculation }}, à titre onéreux et à compter du {{ "now"|date('Y-m-d') }}.

            Kilométrage du véhicule : {{ location.vehicle.km }} kms
            Le locataire certifie être en possession du permis l’autorisant à conduire le présent véhicule.
        </p>
        <br>
        <p>
            <h3>1.2 – État du véhicule</h3>
            Lors de la remise du véhicule et lors de sa restitution, un procès-verbal de l’état du véhicule sera établi entre le locataire et le loueur.

            Le véhicule devra être restitué le même état que lors de sa mise à disposition au locataire. Toutes les détériorations sur le véhicule constatées sur le PV de sortie seront à la charge du locataire.
        </p>
        <br>
        <p>
            <h3>1.3 – Prix de la location du véhicule</h3>
            Les parties s’entendent sur un prix de location {{ location.pricePaid }} euros par jour (calendaires).
        </p>
        <br>
        <p>
            <h3>1.4 – Kilométrage supplémentaires</h3>
            Tout kilomètre réalisé au-delà du forfait indiqué à l’article 1.3 du présent contrat sera facturé au prix de {{ location.announce.price }} euros * le nb de jours supplémentaires.
        </p>
        <br>
        <p>
            <h3>1.5 – Durée et restitution du véhicule</h3>
            Le contrat est à durée indéterminée (à défaut préciser les dates et la durée en jours calendaires). Il pourra y être mis fin par chacune des parties à tout moment en adressant un courrier recommandé en respectant un préavis d’un mois.
        </p>
        <br>
        <p>
            <h3>1.6 – Autres éléments et accessoires</h3>
            Le locataire prendra en charge l’ensemble des charges afférentes à la mise à disposition du véhicule :

            <ul class="list-group">
                <li class="list-group-item">Frais d’entretien du véhicule,</li>
                <li class="list-group-item">Impôts et taxes liés au véhicule,</li>
                <li class="list-group-item">Les frais d’essence,</li>
                <li class="list-group-item">L’assurance du véhicule.</li>
            </ul>
        </p>
        <br>
        <p>
            <h3>1.7 – Clause en cas de litige</h3>
            Les parties conviennent expressément que tout litige pouvant naître de l’exécution du présent contrat relèvera de la compétence du tribunal de commerce.
        </p>
        <br>
        <p>
            Fait le {{ "now"|date('Y-m-d') }}, <br>
            E-motion
        </p>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/payment/partials/_email.html.twig
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Paiement réussi!</h4>
            <p>Votre paiement a bien été éffectuer.</p>
            <p>Ci-joint, votre facture, ainsi que le contrat de location auquel vous avez adhérer.</p>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/payment/partials/_facture.html.twig
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <div class="jumbotron">
            <h3>Facture du {{ "now"|date('Y-m-d') }}</h3>
            <p>Utilisateurs : {{ location.user.fullName }}</p>
            <p>Adresse : {{ location.user.fullAddress }}</p>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Véhicule</th>
                    <th scope="col">Date de début de location</th>
                    <th scope="col">Date de fin de location</th>
                    <th scope="col">Prix a la journée (€/jour)</th>
                    <th scope="col">Prix total (€)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ location.vehicle }}</td>
                    <td>{{ location.startDate|date('Y/m/d H:i') }}</td>
                    <td>{{ location.endDate|date('Y/m/d H:i') }}</td>
                    <td>{{ location.announce.price }}</td>
                    <td>{{ location.pricePaid }}</td>
                </tr>
            </tbody>
        </table>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>